apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-v1-deployment
  #namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hola-v1
  template:
    metadata:
      labels:
        app: hola-v1
    spec:
      containers:
      - name: hola
        image: dedosmedia/hola:v1
        ports:
        - containerPort: 8080
    