apiVersion: v1
kind: Service
metadata:
  name: hola-v1-service
  labels: 
    app: hola-v1
  namespace: hola-app
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    app: hola-v1

---

apiVersion: v1
kind: Service
metadata:
  name: hola-v2-service
  labels: 
    app: hola-v2
  namespace: hola-app
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    app: hola-v2